### ISSUE TITLE
error codes

### ISSUE THREAD

**Issue by j3nsykes** [BelaPlatform/Trill-Arduino#2]
Hello is there any documentations as to what the error codes refer in setup() on serial.print? I'm trying to run a Square and Bar (not at same time) and keep getting error code -3 using the Trill examples. 

I have tried a Teensy 3.2, Adafruit various boards and Arduino Uno all same result. The square does work after a few plug/un-plug restarts but no luck with the Bar. 

I've also tied changing the Grove connector wire but this doesn't make any difference either.

**Comment by j3nsykes** [comment]
Now resolved. Think my issue was using boards with varied voltage pins (eg; Teensy 3.2 has 3.3-5.5V Vin pin) and I had no pull up resistors (as your documentation suggests👍). Now have a consistent output but will leave comment here incase others have issues.

**Comment by disastrid** [comment]
@j3nsykes Glad you resolved it, and especially glad the documentation helped! If you run into issues and have suggestions for the docs we're always happy to hear them.
