### ISSUE TITLE
Compiler warnings on ESP-IDF

### ISSUE THREAD

**Issue by DocSunset** [BelaPlatform/Trill-Arduino#4]
When compiling on ESP-IDF for ESP32, I get the following compiler warnings:

```
ill.cpp.obj
.../Trill.cpp: In member function 'boolean Trill::read()':
.../Trill.cpp:138:17: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
  138 |         boolean ret = true;
      |                 ^~~
```

and

```
.../Trill.cpp: In member function 'void Trill::setNoiseThreshold(uint8_t)':
.../Trill.cpp:267:22: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  267 |         if(threshold > 255)
      |            ~~~~~~~~~~^~~~~
.../Trill.cpp:269:22: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  269 |         if(threshold < 0)
      |            ~~~~~~~~~~^~~
```

It seems the latter error is due to the fact that `threshold` is a `uint8_t` argument. I suppose that the following lines (267-270) could be removed from `Trill.cpp`:

```cpp
if(threshold > 255)
	threshold = 255;
if(threshold < 0)
	threshold = 0;
```

As for the former warning, presumably the last line of `Trill::read()` should be `return ret`, or perhaps `boolean ret` doesn't need to be declared in the first place?

Obviously, since these are mere warnings, it's not a big issue if this is considered not worth fixing, but it seems prudent to squash these warnings anyways. I would be glad to open a PR if that is helpful, although I would need guidance on how to handle `boolean ret` (e.g. return `ret` or get rid of it?).

**Comment by giuliomoro** [comment]
thanks, sorted
